apiVersion : apps/v1
kind: Deployment
metadata:
  name: notfightclubnotfightclubbets 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notfightclubnotfightclubbets
  template:
    metadata:
      labels:
        app: notfightclubnotfightclubbets 
    spec:
      containers:
        - name: notfightclubnotfightclubbets 
          image: p3fightclub.azurecr.io/notfightclubnotfightclubbets
          ports:
          - containerPort: 5001